name: Test

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
      with:
        # Use PAT instead of default Github token, because the default
        # token deliberately will not trigger another workflow run
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install
      run: npm install
      env:
        # GITHUB_TOKEN can't access packages hosted in private repos,
        # even within the same organisation
        NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Build
      run: npm run build
    - name: Test
      run: npm run travis
    - name: Tag
      if: ${{ github.ref == 'refs/heads/master' }}
      run: ./tag.sh
